apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "board-state-metric.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - nodes
    verbs:
      - list
      - get
      - watch